### ISSUE TITLE
Duplicated vagrant startup scripts needed?

### ISSUE THREAD

**Issue by bocytko** [zalando/zmon#11]
The demo and build-env vms have different startup scripts (`zmon/vagrant` and `zmon/build-dev/vagrant`). I had a hard time trying out the build-env vm, because of various issues already solved in the demo vm (broken pip3, missing scm-source and broken locale configuration). There are also other differences like `start-services.sh`, which in the build-env is still targeting the old zmon controller (8080 & http).

This raises the question, whether the duplicated configuration is needed at all. The only crucial difference I see is the `build.sh` execution in the build-env and the difference in docker image start (local vs. remote image).

So one could imagine having both vms share the same scripts. The build-env would then additionally run the `build.sh` to build local docker images and use them in the `start-services.sh` instead of the versions preconfigured for the demo vm. What do you think @hjacobs @Jan-M ?

**Comment by hjacobs** [comment]
I think we might simply delete the "build-env" folder --- Docker images are build on our Go CD and for development you can simply start the individual app (e.g. ZMON Controller) outside of the Vagrant box (as only Java 8 is needed).

**Comment by bocytko** [comment]
Will ZMON Scheduler (guest machine) be then able to access your locally launched ZMON Controller (host) without the hassle to setup reverse port forwarding or ssh?

Having one vm would be enough if it's easy for potential contributors to:
1) access modified source code (easily achieved via mounting host fs from guest)
2) build a new docker image within the vm and start it there (`build.sh` and slightly modified `start-services.sh` taking a new parameter for the docker image version).

**Comment by hjacobs** [comment]
OK, you are right, the other way around is harder (Vagrant Box -> outside Controller)

**Comment by LappleApple** [comment]
Hi @hjacobs @Jan-M @bocytko: Anything more to do here? Can we close?

**Comment by Jan-M** [comment]
Current most convenient way of deploying is now docker compose.

Controller and Eventlog Service now also rely on flyway making the deployment/bootstrap a lot easier.
