### ISSUE TITLE
It is not possible to customize "Clear Alert" message for HipChat notifications.

### ISSUE THREAD

**Issue by sezera** [zalando/zmon#12]
Whenever an Alert is raised or cleared, notification message is always same for Hipchat notifications.
Email notifications have at least a message prefixed automatically, for example: ALERT ENDED: Critical Alert [Alert message]

**Comment by LappleApple** [comment]
Hi @sezera: Are you still experiencing this issue? @hjacobs @Jan-M, did you or someone else fix this?

**Comment by elauria** [comment]
fixed
