### ISSUE TITLE
Data is not collecting

### ISSUE THREAD

**Issue by dimaslv** [zalando/zmon#16]
I have installed ZMON according to manual and have imported check-definitons and entities from zmon-demo github, I have also added some custom check-defs and entities, but the only check collecting is default "Random".
zmon cli show all the entites and checks correclty.
On "Check defs" page the only difference between all the check is Team, which is "Example Team" for "Random" and "ZMON" for others.
"ps" always show "zmon-worker check 1 on ..." for all worker process.
I have tried to run "BLPOP zmon:queue:default" in redis-cli and it always return only "...Random..".
If I understand architecture correctly, then zmon-collector is not pushing new checks to redit, but I don't know how to debug it any further.

P.S. https://demo.zmon.io is also not collecting data since 21.03.16.

**Comment by LappleApple** [comment]
@dimaslv Hello, I'm just seeing this issue now. Very sorry that nobody got back to you. Are you still interested in ZMON? cc @Jan-M

**Comment by dimaslv** [comment]
Hello!
Unfortunately no. But I hope your project someday became more supported and popular as it specs look really great.
Thanks.

**Comment by LappleApple** [comment]
Thanks, @dimaslv.
