### ISSUE TITLE
Where is your code?

### ISSUE THREAD

**Issue by szuecs** [zalando/zmon#17]
Hi!

Don't get me wrong, zmon is really cool and I want to ask questions that I would have if I want to use this project.

Zmon is really nice, but how do I get all the repositories?
How to install zmon it?
Can you suggest server size or number of servers?
Where to put what component?
Why should I use it, if I can not understand how to install it?

Best, sandor

**Comment by Jan-M** [comment]
https://docs.zmon.io/en/latest/installation/requirements.html is always a good start ;-)

And yes README needs a work over, but as it already explains, running it via vagrant or looking at the linked demo gives you a good idea, and both setup scripts are relatively simple.

Hint taken and in the works.

**Comment by LappleApple** [comment]
@Jan-M when do we start working on the READMEs/docs?

**Comment by LappleApple** [comment]
@Jan-M @szuecs Seems this isn't going to change anyt

**Comment by Jan-M** [comment]
Well we have imho proved a lot - the readme links all componentes and recently we replaced the Vagrantbox with Docker compose - I would expect this is more convenient to understand.

**Comment by LappleApple** [comment]
@Jan-M That's great, Jan. Congrats for all your improvements!
