### ISSUE TITLE
Upgrade to Ubuntu 16.04 LTS (Xenial)

### ISSUE THREAD

**Issue by hjacobs** [zalando/zmon#19]

**Comment by hjacobs** [comment]
I stopped working on this as it is not as straightforward as I thought: e.g. the network configuration changed and `--net=host` will not work for the Cassandra image. We probably need to migrate to the Docker networking approach as we did in https://github.com/zalando/zmon-demo

**Comment by hjacobs** [comment]
Our currently used Ubuntu 15.10 (Wily) has its end of life in July 2016: https://wiki.ubuntu.com/Releases

**Comment by Jan-M** [comment]
Now 16.10 is working
