### ISSUE TITLE
Cannot start Cassandra container

### ISSUE THREAD

**Issue by arturmartins** [zalando/zmon#2]
Getting this error after fixing issue #1:

==> default: Error response from daemon: Cannot start container 1e848ddcb52e07cf9f0c8d8e05b48047ffeef65d070e010f5d655dc0dae81e34: Error getting container 1e848ddcb52e07cf9f0c8d8e05b48047ffeef65d070e010f5d655dc0dae81e34 from driver devicemapper: Error mounting '/dev/mapper/docker-8:1-262152-1e848ddcb52e07cf9f0c8d8e05b48047ffeef65d070e010f5d655dc0dae81e34' on '/var/lib/docker/devicemapper/mnt/1e848ddcb52e07cf9f0c8d8e05b48047ffeef65d070e010f5d655dc0dae81e34': no such file or directory

**Comment by hjacobs** [comment]
Uh, this Docker devicemapper error looks familiar --- I don't remember how I fixed it (somewhere else, not in this Vagrant box), but retrying seemed to work for me.

**Comment by hjacobs** [comment]
FYI: I got the cassandra instance running by retrying:

```
vagrant ssh
cd /vagrant/vagrant
./start.sh
# retried start.sh up to three times

**Comment by Jan-M** [comment]
Either rerun start.sh script or if any of the zmon services fail to come up you can use the "start-services.sh" script, which also takes a parameter to start individual services: e.g. "worker"

The device mapper issues seemed to have gone away earlier with the new docker versions, at least for me. Will look into improving the startup scripts, they should not just wait I guess, but also retry the container startup.

Please feel free to report outstanding issues/problems.

**Comment by Jan-M** [comment]
I have now updated to new Ubuntu release, too. Also tested with recent Vagrant box version.

Testing within our teams has not reproduced any more device mapper errors for now, I hope this is true for everyone.
