### ISSUE TITLE
Add support for excluding alerts in dashboards based on alert tags

### ISSUE THREAD

**Issue by iweinzierl** [zalando/zmon#21]
Today, the dashboard already supports a feature to show alerts with specific tags only. It would be also great to support the exact other way around: hide alerts with specific tags.

A simple and maybe easy way could be to just add a "!" in front of the tags you don't want to see in your dashboard:

![screen shot 2016-07-29 at 14 46 41](https://cloud.githubusercontent.com/assets/2050618/17248533/6fc2398e-559b-11e6-9c7b-e0ca57195905.png)

**Comment by Jan-M** [comment]
Right now we filter by:
 - match any team
 - match all tags

How would that work with !?

Not contains any of the !?

**Comment by iweinzierl** [comment]
AFAIK, the filter works like "fetch all but keep only the alerts where tags apply". I would propose to extend the filter so that "fetch all, but keep only the alerts where a) tags apply and b) no 'do-not-include-tag' is set.

**Comment by LappleApple** [comment]
@Jan-M @hjacobs Any changes here since I@iweinzierl filed his request?

**Comment by Jan-M** [comment]
This is live now: @iweinzierl prepend your tag with "!" to not show it.
