### ISSUE TITLE
Add format option to gauge widget

### ISSUE THREAD

**Issue by alnkpa** [zalando/zmon#22]
For a value widget, I can use the format option to define how to display the value. As the gauge widget also displays the value textually, I'd like a similar option there.

**Comment by hjacobs** [comment]
@alnkpa can you create the issue in the ZMON Controller repo please? https://github.com/zalando-zmon/zmon-controller/issues

Thanks!

**Comment by alnkpa** [comment]
Opened https://github.com/zalando-zmon/zmon-controller/issues/319
