### ISSUE TITLE
Add percent format option to value widget

### ISSUE THREAD

**Issue by jrempe** [zalando/zmon#23]
Since some checks might return decimal values to be interpreted as percentage, the percentage formatting option would come in handy.
From https://docs.python.org/3/library/string.html#format-specification-mini-language:
`'%'    Percentage. Multiplies the number by 100 and displays in fixed ('f') format, followed by a percent sign.`

**Comment by LappleApple** [comment]
Hey @Jan-M and @hjacobs: Is this something you agree with? If so, maybe let's add the "Help Wanted" issue.

**Comment by LappleApple** [comment]
@Jan-M and @hjacobs: trying again.

**Comment by hjacobs** [comment]
IIRC this needs to be implemented in the JS frontend.

**Comment by LappleApple** [comment]
Thanks for the fast response, @hjacobs. I appreciate your efforts to keep things moving along.

**Comment by elauria** [comment]
Added Issue on zmon-controller: https://github.com/zalando-zmon/zmon-controller/issues/407

closing this one
