### ISSUE TITLE
aws:cloudformation:logical_id tag for Application ELBs

### ISSUE THREAD

**Issue by jkozlowicz** [zalando/zmon#29]
We want to set up a ZMON check/monitor to fetch and aggregate data from CloudWatch.

What need `aws:cloudformation:logical_id` tag for this for one of our applications. It works but unfortunately only for Classic ELBs. We want to switch types of all the ELBs to ApplicationELB because only they support percentiles in metrics.

We will request adding the `aws:cloudformation:logical_id` tag from Amazon for ApplicationELBs 
so that it can be picked up by ZMON.

**Comment by Jan-M** [comment]
To my understanding AWS API does not provide that tag for ALBs so nothing we can do at the moment.

@hjacobs correct?
