### ISSUE TITLE
Add more elaborate dashboard example to the Vagrant box

### ISSUE THREAD

**Issue by hjacobs** [zalando/zmon#6]
`vagrant up` works fine for me (Ubuntu 15.10 with Vagrant 1.7.4), but the example dashboard only has a very simple sample alert:
![screenshot_2015-12-05_21-10-11](https://cloud.githubusercontent.com/assets/510328/11609948/a4477208-9b94-11e5-8688-a51e8b4b2169.png)

We should add some dashboard widgets and more example checks/alerts to have a more convincing first impression :smile:

**Comment by elauria** [comment]
+1 on this, also to ease development of the frontend.

this is something i already talked with Jan and will soon do something about

**Comment by LappleApple** [comment]
@hjacobs @Jan-M Was this done? Can we close the issue?

**Comment by roskenet** [comment]
For me the Alert Definitions in the vagrant setup doesn't work at all:
When running `vagrant up`:

==> default: Creating alert definition ...
==> default:  EXCEPTION OCCURRED: 500 Server Error: Internal Server Error for url: https://localhost:8443/api/v1/alert-definitions/
==> default: HTTP error: 500 - Internal Server Error

multiple times.

**Comment by Jan-M** [comment]
For me Vagrant box is obsolete, the readme points to docker compose and this is a much faster initial deployment to get going.

But does not change that the initial examples could see some more useful examples.
