### ISSUE TITLE
The readme should be clearer about the installation of zmon-cli 

### ISSUE THREAD

**Issue by Hachmaninow** [zalando/zmon#8]
Currently the part in the readme is a little confusing, as there are two possibilities:
1) install on the host, as there are the examples
2) install within vagrant box, as there the zmon base url is preconfigured

The readme should be clear about either way.

**Comment by hjacobs** [comment]
:+1:

**Comment by LappleApple** [comment]
Will work on this.

**Comment by LappleApple** [comment]
@Jan-M Hey, did you do this? If so, we can close the Issue.

**Comment by LappleApple** [comment]
@Jan-M @hjacobs Didn't get a response, trying again.

**Comment by Jan-M** [comment]
I updated the readme some time ago as we now rely on docker compose.

But took some more minutes now to make it even clearer.
